In [1]:
import numpy as numpy
import pandas as pd

In [2]:
df = pd.read_csv("../Data/marketing_funnel_sample.csv")
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,date,month,day
0,2019-11-01 02:57:40+00:00,view,13400599,2053013557066334713,NaN,NaN,167.29,530773648,86c5cd2d-2a11-4073-ad4e-a783d40a7674,2019-11-01,11,1
1,2019-10-01 05:10:02+00:00,view,12301111,2053013556311359947,construction.tools.drill,dewalt,220.41,552807394,c6daf1fa-9614-42c5-98e5-d15d2b3854c9,2019-10-01,10,1
2,2019-11-01 01:55:49+00:00,view,1004668,2053013555631882655,electronics.smartphone,bq,112.20,563944256,51266512-42b4-4a46-8336-d1fb709833ae,2019-11-01,11,1
3,2019-10-01 04:40:50+00:00,view,4804055,2053013554658804075,electronics.audio.headphone,apple,188.73,555160144,ad7b7757-40aa-425c-b3fd-2b50b35012c8,2019-10-01,10,1
4,2019-10-01 06:40:03+00:00,view,32801022,2055156924273394455,NaN,NaN,163.02,522324933,590d629f-9b45-402e-b65c-1b4fed343673,2019-10-01,10,1

### Dataset information

In [3]:
df.shape

(10000, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     10000 non-null  object
 1   event_type     10000 non-null  object
 2   product_id     10000 non-null  int64
 3   category_id    10000 non-null  int64
 4   category_code  6807 non-null   object
 5   brand          8571 non-null   object
 6   price          10000 non-null  float64
 7   user_id        10000 non-null  int64
 8   user_session   10000 non-null  object
 9   date           10000 non-null  object
 10  month          10000 non-null  int64
 11  day            10000 non-null  int64
dtypes: float64(1), int64(5), object(6)
memory usage: 937.6+ KB

In [5]:
df.describe()

,product_id,category_id,price,user_id,month,day
count,1.000000e+04,1.000000e+04,10000.000000,1.000000e+04,10000.000000,10000.0
mean,1.037130e+07,2.056898e+18,286.831200,5.329150e+08,10.493500,1.0
std,1.150982e+07,1.732327e+16,348.415616,1.835802e+07,0.499983,0.0
min,1.002098e+06,2.053014e+18,0.000000,3.700767e+08,10.000000,1.0
25%,1.005157e+06,2.053014e+18,65.897500,5.156691e+08,10.000000,1.0
50%,5.100337e+06,2.053014e+18,161.910000,5.281673e+08,10.000000,1.0
75%,1.570011e+07,2.053014e+18,358.310000,5.499151e+08,11.000000,1.0
max,6.050000e+07,2.173217e+18,2574.070000,5.663467e+08,11.000000,1.0

### Check missing values

In [6]:
df.isnull().sum()

event_time          0
event_type          0
product_id          0
category_id         0
category_code    3193
brand            1429
price               0
user_id             0
user_session        0
date                0
month               0
day                 0
dtype: int64

### Handle missing values

In [7]:
df['brand'] = df['brand'].fillna('Unknown')
df['category_code'] = df['category_code'].fillna('Unknown')

### Remove duplicates

In [8]:
df = df.drop_duplicates()

### Convert Date column

In [9]:
df['event_time'] = pd.to_datetime(df['event_time'])

### Create Additional Features

In [10]:
df['hour'] = df['event_time'].dt.hour
df['weekday'] = df['event_time'].dt.day_name()

### Save Cleaned Dataset

In [11]:
df.to_csv("../data/cleaned_marketing_funnel.csv", index=False)